// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG4fkWySBK1S6GfWiMTJ0xDGmUFxWDdMA',
    appId: '1:986364414232:web:33887c31a2c2473382766d',
    messagingSenderId: '986364414232',
    projectId: 'flutter-todo-app-188bb',
    authDomain: 'flutter-todo-app-188bb.firebaseapp.com',
    storageBucket: 'flutter-todo-app-188bb.appspot.com',
    measurementId: 'G-2RZ4YEXWM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1DOilewlNWPSeylaLkE2B_1Fdu1rAMeo',
    appId: '1:986364414232:android:91c122fa5cd1817882766d',
    messagingSenderId: '986364414232',
    projectId: 'flutter-todo-app-188bb',
    storageBucket: 'flutter-todo-app-188bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKSMGuBEk0IAgrQrNGxyteAOEUYkbcWJo',
    appId: '1:986364414232:ios:95f5cdf1b3e4189d82766d',
    messagingSenderId: '986364414232',
    projectId: 'flutter-todo-app-188bb',
    storageBucket: 'flutter-todo-app-188bb.appspot.com',
    iosClientId: '986364414232-4kbvqkfas3dn2crkhth6kg09ci5d5c2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKSMGuBEk0IAgrQrNGxyteAOEUYkbcWJo',
    appId: '1:986364414232:ios:95f5cdf1b3e4189d82766d',
    messagingSenderId: '986364414232',
    projectId: 'flutter-todo-app-188bb',
    storageBucket: 'flutter-todo-app-188bb.appspot.com',
    iosClientId: '986364414232-4kbvqkfas3dn2crkhth6kg09ci5d5c2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );
}
